alias nta='cd ~/nta'
alias npc='cd $NUPIC'
alias wall='cd ~/nta/nupic.wallboard'
alias nwiki='cd ~/nta/nupic.wiki'
alias ntools='cd ~/nta/nupic.tools'
alias norg='cd ~/nta/numenta.org'
alias ncore='cd ~/nta/nupic.core'
alias pycept='cd ~/nta/pycept'
